// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/EventFormats.proto

package net.lunikon.akka.persistence.serialization;

public final class EventFormats {
  private EventFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BookedMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 amount = 1;
    /**
     * <code>required int64 amount = 1;</code>
     */
    boolean hasAmount();
    /**
     * <code>required int64 amount = 1;</code>
     */
    long getAmount();
  }
  /**
   * Protobuf type {@code BookedMessage}
   */
  public static final class BookedMessage extends
      com.google.protobuf.GeneratedMessage
      implements BookedMessageOrBuilder {
    // Use BookedMessage.newBuilder() to construct.
    private BookedMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BookedMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BookedMessage defaultInstance;
    public static BookedMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BookedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BookedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              amount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.lunikon.akka.persistence.serialization.EventFormats.internal_static_BookedMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.lunikon.akka.persistence.serialization.EventFormats.internal_static_BookedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.class, net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<BookedMessage> PARSER =
        new com.google.protobuf.AbstractParser<BookedMessage>() {
      public BookedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookedMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BookedMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 amount = 1;
    public static final int AMOUNT_FIELD_NUMBER = 1;
    private long amount_;
    /**
     * <code>required int64 amount = 1;</code>
     */
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 amount = 1;</code>
     */
    public long getAmount() {
      return amount_;
    }

    private void initFields() {
      amount_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, amount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, amount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.lunikon.akka.persistence.serialization.EventFormats.BookedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.lunikon.akka.persistence.serialization.EventFormats.internal_static_BookedMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.lunikon.akka.persistence.serialization.EventFormats.internal_static_BookedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.class, net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.Builder.class);
      }

      // Construct using net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        amount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.lunikon.akka.persistence.serialization.EventFormats.internal_static_BookedMessage_descriptor;
      }

      public net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage getDefaultInstanceForType() {
        return net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.getDefaultInstance();
      }

      public net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage build() {
        net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage buildPartial() {
        net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage result = new net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.amount_ = amount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage) {
          return mergeFrom((net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage other) {
        if (other == net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage.getDefaultInstance()) return this;
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAmount()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.lunikon.akka.persistence.serialization.EventFormats.BookedMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 amount = 1;
      private long amount_ ;
      /**
       * <code>required int64 amount = 1;</code>
       */
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 amount = 1;</code>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>required int64 amount = 1;</code>
       */
      public Builder setAmount(long value) {
        bitField0_ |= 0x00000001;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 amount = 1;</code>
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BookedMessage)
    }

    static {
      defaultInstance = new BookedMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BookedMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BookedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BookedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protobuf/EventFormats.proto\"\037\n\rBookedM" +
      "essage\022\016\n\006amount\030\001 \002(\003B.\n*net.lunikon.ak" +
      "ka.persistence.serializationH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BookedMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BookedMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BookedMessage_descriptor,
              new java.lang.String[] { "Amount", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
