// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/StateFormats.proto

package net.lunikon.akka.persistence.serialization;

public final class StateFormats {
  private StateFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AccountMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 balance = 1;
    /**
     * <code>required int64 balance = 1;</code>
     */
    boolean hasBalance();
    /**
     * <code>required int64 balance = 1;</code>
     */
    long getBalance();
  }
  /**
   * Protobuf type {@code AccountMessage}
   */
  public static final class AccountMessage extends
      com.google.protobuf.GeneratedMessage
      implements AccountMessageOrBuilder {
    // Use AccountMessage.newBuilder() to construct.
    private AccountMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AccountMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AccountMessage defaultInstance;
    public static AccountMessage getDefaultInstance() {
      return defaultInstance;
    }

    public AccountMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AccountMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              balance_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.lunikon.akka.persistence.serialization.StateFormats.internal_static_AccountMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.lunikon.akka.persistence.serialization.StateFormats.internal_static_AccountMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.class, net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<AccountMessage> PARSER =
        new com.google.protobuf.AbstractParser<AccountMessage>() {
      public AccountMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccountMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AccountMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 balance = 1;
    public static final int BALANCE_FIELD_NUMBER = 1;
    private long balance_;
    /**
     * <code>required int64 balance = 1;</code>
     */
    public boolean hasBalance() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 balance = 1;</code>
     */
    public long getBalance() {
      return balance_;
    }

    private void initFields() {
      balance_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBalance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, balance_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, balance_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AccountMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.lunikon.akka.persistence.serialization.StateFormats.AccountMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.lunikon.akka.persistence.serialization.StateFormats.internal_static_AccountMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.lunikon.akka.persistence.serialization.StateFormats.internal_static_AccountMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.class, net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.Builder.class);
      }

      // Construct using net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        balance_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.lunikon.akka.persistence.serialization.StateFormats.internal_static_AccountMessage_descriptor;
      }

      public net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage getDefaultInstanceForType() {
        return net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.getDefaultInstance();
      }

      public net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage build() {
        net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage buildPartial() {
        net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage result = new net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.balance_ = balance_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage) {
          return mergeFrom((net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage other) {
        if (other == net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage.getDefaultInstance()) return this;
        if (other.hasBalance()) {
          setBalance(other.getBalance());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBalance()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.lunikon.akka.persistence.serialization.StateFormats.AccountMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 balance = 1;
      private long balance_ ;
      /**
       * <code>required int64 balance = 1;</code>
       */
      public boolean hasBalance() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 balance = 1;</code>
       */
      public long getBalance() {
        return balance_;
      }
      /**
       * <code>required int64 balance = 1;</code>
       */
      public Builder setBalance(long value) {
        bitField0_ |= 0x00000001;
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 balance = 1;</code>
       */
      public Builder clearBalance() {
        bitField0_ = (bitField0_ & ~0x00000001);
        balance_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AccountMessage)
    }

    static {
      defaultInstance = new AccountMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AccountMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AccountMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AccountMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protobuf/StateFormats.proto\"!\n\016Account" +
      "Message\022\017\n\007balance\030\001 \002(\003B.\n*net.lunikon." +
      "akka.persistence.serializationH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AccountMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AccountMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AccountMessage_descriptor,
              new java.lang.String[] { "Balance", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
